### ISSUE TITLE
Develop a cart2geo(Point, refPoint) >> (lat, lon) function 

### ISSUE THREAD

**Issue by nico1as** [galleon/gym-jsbsim#11]
develop a cart2geo(Point, refPoint) >> (lat, lon) function to debug the taxi environment

**Comment by jyotsnab** [comment]
the output is updated to give [cartesian coordinates, distance, heading, (lat,long)]

**Comment by jyotsnab** [comment]
> the output is updated to give [cartesian coordinates, distance, heading, (lat,long)]

(lat,long) of the point on the path from which distance and heading with respect to refPoint are measured.
