### ISSUE TITLE
Collect all JSBSim attribute from jsbsim_exec var

### ISSUE THREAD

**Issue by nico1as** [galleon/gym-jsbsim#12]
find out if it is possible to collect all JSBSim parameters from the jsbsim_exec instance

**Comment by bgaudron** [comment]
I changed the Enum class Catalog for a dict class DynamicCatalog. Catalog is now an instantiation of DynamicCatalog.
That way Catalog is not a static catalog with all properties of JsbsimCatalog and MyCatalog but it is a catalog with only properties used in the task and in the simulation collected from the jsbsim_exec instance after its initialization. 
JsbsimCatalog doesn't need to store all existing jsbsim properties, so now it contains only properties for which need to add a feature like min/max or update function.
