### ISSUE TITLE
add test in the code

### ISSUE THREAD

**Issue by nico1as** [galleon/gym-jsbsim#14]

**Comment by nico1as** [comment]
more particularly, we need testes for:
 * my_catalogs update functions (ie: validate that delta_heading is still valide for example)
 * get_state() and set_state()
 * normalisation of states and actions (that implies to have min and max values defined in nametuple object)

**Comment by bgaudron** [comment]
Tests on the main features have been commited 2c9f82c3d01108d3fb905203700b5c6291a7b5c5 in [`tests`](https://github.com/galleon/gym-jsbsim/tree/new/gym_jsbsim/tests).
With tests for:
- my_catalogs update functions in [`test_properties.py`](https://github.com/galleon/gym-jsbsim/blob/new/gym_jsbsim/tests/test_properties.py)
- get_state() and set_state() in [`test_simulation.py`](https://github.com/galleon/gym-jsbsim/blob/new/gym_jsbsim/tests/test_simulation.py)
- normalisation of states and actions in [`test_tasks.py`](https://github.com/galleon/gym-jsbsim/blob/new/gym_jsbsim/tests/test_tasks.py)

**Comment by nico1as** [comment]
take a look on travis to test on every commit...
