### ISSUE TITLE
Add setup.py for generating python package

### ISSUE THREAD

**Issue by galleon** [galleon/gym-jsbsim#16]
Add a setup.py to generate the package. You can have a look to new_gal branch.

**Comment by nico1as** [comment]
Use 
- DockerFile
- travis for unit test

**Comment by nico1as** [comment]
pip install works good.

**Comment by nico1as** [comment]
works for linux and mac ... still issues on windows
pipy account as been created by guillaume

**Comment by nico1as** [comment]
it is in the doto list of shapely ... so let windows user install shapely first...
