### ISSUE TITLE
fix order of next centerline point

### ISSUE THREAD

**Issue by nico1as** [galleon/gym-jsbsim#20]
<img width="768" alt="Screenshot 2019-07-24 at 11 21 49" src="https://user-images.githubusercontent.com/10497115/61781816-51aef200-ae05-11e9-8336-00424d36bc29.png">

**Comment by jyotsnab** [comment]
Corrected
![taxi_env_example](https://user-images.githubusercontent.com/14355820/63270228-066af080-c298-11e9-9300-b6000f4cf825.gif)
