### ISSUE TITLE
fix heading value of next centerline point

### ISSUE THREAD

**Issue by nico1as** [galleon/gym-jsbsim#21]

**Comment by jyotsnab** [comment]
Corrected!
![taxi_env_example](https://user-images.githubusercontent.com/14355820/63270073-b55afc80-c297-11e9-875b-148a2bd62f49.gif)

**Comment by jyotsnab** [comment]
Corrected!
![taxi_env_example](https://user-images.githubusercontent.com/14355820/63270073-b55afc80-c297-11e9-875b-148a2bd62f49.gif)

**Comment by nico1as** [comment]
may be there is still an issue with a +- 180 degree ... and a strong behavior in regards to the closest point whern this one is behind the aircraft ... To check.
