### ISSUE TITLE
Environment returning nan observations even if not in a terminal observation

### ISSUE THREAD

**Issue by fteicht** [galleon/gym-jsbsim#22]
So my algorithm happens to explore some problematic observations from the environment point of view.

For instance, at some point the algorithm asks the environment to make a step from the following observation:

```(array([-0.00422987]), array([0.08353463]), array([-0.02629647]), array([700.9670662]), array([-0.08036866]), array([0.1422439]), array([-0.05053454]))```

which is indicated by the environment as *non terminal*, using the following action:

```(array([-0.19984015]), array([0.39972021]), array([1.]), array([0.62978317]))```.

The environment returns a ```nan``` reward and the following *non terminal* observation:

```(array([nan]), array([nan]), array([nan]), array([0.]), array([nan]), array([nan]), array([nan]))```.

Since my algorithm is agnostic and does not know the form (or type) of the incoming observation, it is very difficult for me to check if the observation is valid or not. I think the environment should check it somehow, then set the ```termination``` flag to ```True``` or raise an exception.

**Comment by galleon** [comment]
2 problems:
  - NaN do not lead to a terminal state
  - setState / getState potential problem (is it IW)

split in 2 issues. one for NaN & the other regarding deepcopy of jsbsim.

**Comment by galleon** [comment]
Meanwhile @fteicht  is reimplementing IW in "AIRLAPS"
