### ISSUE TITLE
Implicit assumption on python version

### ISSUE THREAD

**Issue by garibarba** [galleon/gym-jsbsim#24]
This line https://github.com/galleon/gym-jsbsim/blob/64a64eaa6a2a7d3b3fa1ddaa50d18116505a768b/gym_jsbsim/catalogs/property.py#L5 implies a requirement on `python>=3.7` since the `defaults` parameter is only available from that version (see https://docs.python.org/3/library/collections.html#collections.namedtuple).

Should we add a python version check in `__init__.py`?
e.g.
```
import sys
if (sys.version_info.major < 3 or (sys.version_info.major >= 3 and sys.version_info.minor < 7)):
    raise Exception("Python 3.7 or a more recent version is required.")
```

**Comment by galleon** [comment]
@bgaudron have a look whether or not we need really only 3.7 & make sure we have a setup script enforcing the python version we need

/assign @bgaudron

**Comment by galleon** [comment]
As discussed opened  #27. The other one needed is #16 
@fteicht is working on [#22](https://scm.airbusdigital.com/datascience/airlaps/issues/22)

closing
