### ISSUE TITLE
add a python version test in property file for nametuple setup

### ISSUE THREAD

**Issue by nico1as** [galleon/gym-jsbsim#28]
namtuple is declare with a python 3.7 syntax:
https://github.com/galleon/gym-jsbsim/blob/a3853792aa57bb23e19434329c446aedb9c1c99d/gym_jsbsim/catalogs/property.py#L5

add a **if** statement to declare it according to python version

see: https://stackoverflow.com/questions/11351032/namedtuple-and-default-values-for-optional-keyword-arguments for the different declaration according to python version

**Comment by bgaudron** [comment]
Added line https://github.com/galleon/gym-jsbsim/blob/2134cc3df74004cbf619c842e37dda5d80a5f0d4/gym_jsbsim/catalogs/property.py#L7 in Property definition.
It's now working with python 3.6 too.
