### ISSUE TITLE
JSBSim A320 model: develop & optimise autopilot in regards to slow velocity

### ISSUE THREAD

**Issue by nico1as** [galleon/gym-jsbsim#30]
PID coefficients should be optimised for velocity between 0 and 20 knots...

**Comment by galleon** [comment]
@garibarba suggested to check the FGMEMBERS repo
Consider to contribute this to JSBSIM

**Comment by nico1as** [comment]
may be specified that this is a AP dedicated for ground (ie: taxi) as there is a PID for brakes that have been put in place ...
