### ISSUE TITLE
checked if all centerline points are stored

### ISSUE THREAD

**Issue by nico1as** [galleon/gym-jsbsim#31]
It seems that centerline point are too away from each others. Curves are then not well represented. Checked if all points are stored in the centerline point list.

![Screenshot 2019-09-06 at 11 43 57](https://user-images.githubusercontent.com/10497115/64418817-faef3600-d09b-11e9-9e02-d860f4fd7fdf.png)

**Comment by jyotsnab** [comment]
Fixed! Now there are much more points at curves and similar number of points as before for straight lines.
