### ISSUE TITLE
Remove shapely dependency

### ISSUE THREAD

**Issue by bgaudron** [galleon/gym-jsbsim#39]
Shapely library is used to compute distances in [taxi_utils2.py](https://github.com/galleon/gym-jsbsim/blob/new/gym_jsbsim/envs/taxi_utils2.py) but doesn't have a windows version available on Pypi so for now `gym-jsbsim` package can't be install directly with `pip install gym-jsbsim` on windows (we first have to install shapely from the wheels at http://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely). 
It should be good to replace Shapely with another library available on Pypi or implementing directly the needed functions so that the package can be pip installable on Linux, MacOS and Windows.

**Comment by galleon** [comment]
Shapely is addressing the problem so let's wait until it is solved https://github.com/Toblerity/Shapely/issues/367

**Comment by mwtoews** [comment]
FYI, Windows binary wheels are finally available on PyPI.
```
pip install shapely>=1.7.0
```
