### ISSUE TITLE
Manual pip install fails due to missing file in the distribution

### ISSUE THREAD

**Issue by fteicht** [galleon/gym-jsbsim#51]
Output of bash:
```
[ec2-user@ip-172-31-17-160 gym-jsbsim]$ pip3.7 install . --user
Processing /home/ec2-user/gym-jsbsim
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-od9dmgtr-build/setup.py", line 14, in <module>
        os.replace(os.path.join(from_path, air, f), os.path.join(to_path, air, f))
    FileNotFoundError: [Errno 2] No such file or directory: 'gym_jsbsim/docs/aircraft/A320/A320.xml' -> 'gym_jsbsim/jsbsim/aircraft/A320/A320.xml'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-od9dmgtr-build/
```

**Comment by fteicht** [comment]
IMHO the README.md should indicate how to install gym-jsbsim from source (since the automated pip install fails on some linux distributions, see issue #50 ). Specifically, users have t manually copy files from jsbsim to gym-jsbsim, which is not a standard manual pip install procedure.

**Comment by garibarba** [comment]
This should work:

- At clone time:
```
git clone --recurse-submodules [...]
```

- If you already cloned this repo:
```
git submodule update --init --recursive
```

**Comment by fteicht** [comment]
I agree. The point is that the README.md should indicate that this repo relies on submodules (i.e. other repos). Thus people can know that they have to do a recurse-submodules cloning.

**Comment by galleon** [comment]
Add a new section to the README.md
