### ISSUE TITLE
Whether does it only surport A320? How can I make the package useful for the control of F16?

### ISSUE THREAD

**Issue by theorynice** [galleon/gym-jsbsim#57]
Thanks for your job, as the mention above,how can I use the package to train F16? whether I need to  make a autopilot xml file for F16?

**Comment by galleon** [comment]
Thanks for your interest. Using F16 should not be difficult. You can use the `define_aircraft` method on the `Task` to change your aircraft.
I know that for some task we have tweaked the aircraft models. Can you share you you want to learn ?
Happy to help if you face some difficulties.

**Comment by theorynice** [comment]
Thanks for your instant replyment. My job is to train  Aerobatic Maneuvers(such as cobra maneuver）for f16, but so far I have no idea.
