### ISSUE TITLE
Using gym-jsbsim with which library?

### ISSUE THREAD

**Issue by alicanko** [galleon/gym-jsbsim#58]
Hi there, I am trying to use gym-jsbsim with Stable Baselines. However I get errors about action and observation space types since Stable Baselines accept Box type not Tuple. Can you recommend a library to directly use with gym-jsbsim?

Thanks.

_AssertionError: The algorithm only supports <class 'gym.spaces.box.Box'> as action spaces but Tuple(Box(-1.0, 1.0, (1,), float64), Box(-1.0, 1.0, (1,), float64), Box(-1.0, 1.0, (1,), float64), Box(0.0, 0.9, (1,), float64)) was provided_

**Comment by nico1as** [comment]
Hi, give a try with rllib ... Or cast/uncast the Tuple(Box(1,),Box(1,),...)  Action Space to Box(n,) manually 
Best,

**Comment by galleon** [comment]
@alicanko Have you manage to get rid of your problem ?

**Comment by alicanko** [comment]
Not really. I went back to use Gor-Ren repo with stable_baselines. It works fine.
