### ISSUE TITLE
what the reward up to in heading task can I think the train end? 

### ISSUE THREAD

**Issue by theorynice** [galleon/gym-jsbsim#59]

**Comment by galleon** [comment]
@theorynice Not sure I understand your question. Are you wondering what is the reward for this task ?

**Comment by theorynice** [comment]
Yes, it is.

**Comment by nico1as** [comment]
the reward could be find here: https://github.com/galleon/gym-jsbsim/blob/96cc92bd57dc8caf6318b945bd9604c5d6277f30/gym_jsbsim/envs/heading_control_task.py#L56
