### ISSUE TITLE
How can I find all properties?

### ISSUE THREAD

**Issue by Zhulongtao6** [galleon/gym-jsbsim#60]
Some properties are used in code, but they aren't written on JSBSim Reference Manual.For example,"ap/vg-hold" is used in jsb_catalog.py but it can't be found on JSBSim Reference Manual. So I want to now where can I find all properties?

**Comment by nico1as** [comment]
hi, this particular property comes from the `A320ap.xml` [(link)](https://github.com/galleon/gym-jsbsim/blob/96cc92bd57dc8caf6318b945bd9604c5d6277f30/gym_jsbsim/docs/aircraft/A320/A320ap.xml#L4) and added in `jsb_catalog.py`
Added custom properties linked to RL environment could be find in `my_catalog.py`
