### ISSUE TITLE
A Class for each GYM environment

### ISSUE THREAD

**Issue by nico1as** [galleon/gym-jsbsim#8]
make a class for each gym env that allowed to parametrise state / action set, reward and others features like simulation frequency, aircraft ...

**Comment by bgaudron** [comment]
This is now implemented via commit ace61c2bca4fdeaf460843f0317495ef9577428e. Each task is now a subclass of the Task class and can override default values of frequencies, state/action, init conditions, reward...
The Task class also implements 'define' methods you can call to modify these features from the task attribute of the gym env.
To change init_conditions do:
`env.task.define_init_conditions( new_init_conditions )`
